version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.24
    working_directory: /home/circleci/go/src/github.com/viocle/dataloaden
    steps:
      - checkout
      - run: go generate ./example/... && if [[ $(git diff) ]] ; then echo "you need to run go generate" ; git diff ; exit 1 ; fi
      - run: go test -bench=. -benchmem -v ./example/...
      - run: go test -bench=. -benchmem -v ./example/... -race
      - run: go test -coverprofile=coverage.txt -covermode=atomic ./example && bash <(curl -s https://codecov.io/bash)
