package generator

import "text/template"

var tpl = template.Must(template.New("generated").
	Funcs(template.FuncMap{
		"lcFirst":                 lcFirst,
		"loadThunkMissReturnType": LoadThunkMissReturnType,
	}).
	Parse(`
// Code generated by github.com/viocle/dataloaden, DO NOT EDIT.

package {{.Package}}

import (
    "sync"
    "time"

    {{if .KeyType.ImportPath}}"{{.KeyType.ImportPath}}"{{end}}
    {{if .ValType.ImportPath}}"{{.ValType.ImportPath}}"{{end}}
)

// {{.Name}}Config captures the config to create a new {{.Name}}
type {{.Name}}Config struct {
	// Fetch is a method that provides the data for the loader
	Fetch func(keys []{{.KeyType.String}}) ([]{{.ValType.String}}, []error)

	// Wait is how long to wait before sending a batch
	Wait time.Duration

	// MaxBatch will limit the maximum number of keys to send in one batch, 0 = no limit
	MaxBatch int

	{{ if not .DisableCacheExpiration }}
	// ExpireAfter determines how long until cached items expire. Set to 0 to disable expiration
	ExpireAfter time.Duration
	{{ end }}

	// HookBeforeFetch is called right before a fetch is performed
	HookBeforeFetch func(keys []{{.KeyType.String}}, loaderName string)

	// HookAfterFetch is called right after a fetch is performed
	HookAfterFetch func(keys []{{.KeyType.String}}, loaderName string)

	// HookAfterSet is called after a value is set in the cache
	HookAfterSet func(key {{.KeyType.String}}, value {{.ValType.String}})

	// HookAfterClear is called after a value is cleared from the cache
	HookAfterClear func(key {{.KeyType.String}})

	// HookAfterClearAll is called after all values are cleared from the cache
	HookAfterClearAll func()
	
	// HookAfterExpired is called after a value is cleared in the cache due to expiration
	HookAfterExpired func(key {{.KeyType.String}})
}

{{ if not .DisableCacheExpiration }}
// {{.Name}}CacheItem defines a cache item when using dataloader cache expiration where expireAfter > 0 
type {{.Name}}CacheItem struct {
	// Expires contains the time this CacheItem expires
	Expires int64

	// Value contains the cached {{.ValType.String}}
	Value {{.ValType.String}}
}

// expired returns true if the cache item has expired
func (c *{{.Name}}CacheItem) expired(now int64) bool {
	return c.Expires < now
}

{{ end }}
// New{{.Name}} creates a new {{.Name}} given a fetch, wait, and maxBatch
func New{{.Name}}(config {{.Name}}Config) *{{.Name}} {
	l := &{{.Name}}{
		fetch: config.Fetch,
		wait: config.Wait,
		maxBatch: config.MaxBatch,
		{{ if not .DisableCacheExpiration }}
		expireAfter:config.ExpireAfter.Nanoseconds(),
		{{ end }}
		hookBeforeFetch: config.HookBeforeFetch,
		hookAfterFetch: config.HookAfterFetch,
		hookAfterSet: config.HookAfterSet,
		hookAfterClear: config.HookAfterClear,
		hookAfterClearAll: config.HookAfterClearAll,
		hookAfterExpired:  config.HookAfterExpired,
	}
	l.batchPool = sync.Pool{
		New: func() interface{} {
			return l.createNewBatch()
		},
	}
	l.unsafeBatchSet()
	return l
}

// {{.Name}} batches and caches requests          
type {{.Name}} struct {
	// this method provides the data for the loader
	fetch func(keys []{{.KeyType.String}}) ([]{{.ValType.String}}, []error)

	// lazily created cache
	{{ if not .DisableCacheExpiration }}
	cacheExpire map[{{.KeyType.String}}]*{{.Name}}CacheItem
	{{ end }}
	cache map[{{.KeyType.String}}]{{.ValType.String}}

	// the current batch. keys will continue to be collected until timeout is hit,
	// then everything will be sent to the fetch method and out to the listeners
	batch *{{.Name|lcFirst}}Batch

	// how long to done before sending a batch
	wait time.Duration

	// this will limit the maximum number of keys to send in one batch, 0 = no limit
	maxBatch int

	{{ if not .DisableCacheExpiration }}
	// the amount of nanoseconds a cache item should remain valid. This will determine if cache expiration will be used, 0 = no expiration
	expireAfter int64

	{{ end }}
	// mutex to prevent races
	mu sync.Mutex

	// HookBeforeFetch is called right before a fetch is performed
	hookBeforeFetch func(keys []{{.KeyType.String}}, loaderName string)

	// HookAfterFetch is called right after a fetch is performed
	hookAfterFetch func(keys []{{.KeyType.String}}, loaderName string)

	// HookAfterSet is called after a value is primed in the cache
	hookAfterSet func(key {{.KeyType.String}}, value {{.ValType.String}})

	// HookAfterClear is called after a value is cleared from the cache
	hookAfterClear func(key {{.KeyType.String}})

	// HookAfterClearAll is called after all values are cleared from the cache
	hookAfterClearAll func()
	
	// HookAfterExpired is called after a value is cleared in the cache due to expiration
	hookAfterExpired func(key {{.KeyType.String}})

	// pool of batches
	batchPool sync.Pool
}

type {{.Name|lcFirst}}Batch struct {
	now     int64
	done    chan struct{}
	keysMap map[{{.KeyType}}]int
	keys    []{{.KeyType}}
	data    []{{.ValType.String}}
	errors   []error
	closing bool
}

// Load a {{.ValType.Name}} by key, batching and caching will be applied automatically
func (l *{{.Name}}) Load(key {{.KeyType.String}}) ({{.ValType.String}}, error) {
	v, f := l.LoadThunk(key)
	if f != nil {
		return f()
	}
	return v, nil
}

// unsafeBatchSet creates a new batch if one does not exist, otherwise it will reuse the existing batch
func (l *{{.Name}}) unsafeBatchSet() {
	if l.batch == nil {
		b := l.batchPool.Get().(*{{.Name|lcFirst}}Batch)
		// reset
		clear(b.keysMap)
		clear(b.keys)
		l.batch = &{{.Name|lcFirst}}Batch{now: 0, done: make(chan struct{}), keysMap: b.keysMap, keys: b.keys[:0], data: nil, errors: nil}
	} else if l.batch.now == 0 {
		// have a batch but first use, set the start time
		l.batch.now = time.Now().UnixNano()
	}
}

// createNewBatch creates a new batch
func (l *{{.Name}}) createNewBatch() *{{.Name|lcFirst}}Batch {
	return &{{.Name|lcFirst}}Batch{now: 0, done: make(chan struct{}), keysMap: make(map[{{.KeyType.String}}]int, l.maxBatch), keys: make([]{{.KeyType.String}}, 0, l.maxBatch), data: nil, errors: nil}
}

// LoadThunk returns a function that when called will block waiting for a {{.ValType.Name}}.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *{{.Name}}) LoadThunk(key {{.KeyType.String}}) ({{.ValType.String}}, func() ({{.ValType.String}}, error)) {
	l.mu.Lock()
	{{ if not .DisableCacheExpiration }}
	if l.expireAfter <= 0 && len(l.cache) > 0 {
		// not using cache expiration
		if it, ok := l.cache[key]; ok {
			l.mu.Unlock()
			return it, nil
		}
		l.unsafeBatchSet()
	} else if l.expireAfter > 0 && len(l.cacheExpire) > 0 {
		// using cache expiration
		l.unsafeBatchSet()
		if it, ok := l.cacheExpire[key]; ok {
			if it != nil && !it.expired(l.batch.now) {
				l.mu.Unlock()
				return it.Value, nil
			}
			// cache item has expired, clear from cache
			delete(l.cacheExpire, key)
			if l.hookAfterExpired != nil {
				l.hookAfterExpired(key)
			}
		}
	} else {
		// no cache
		l.unsafeBatchSet()
	}
	{{ else }}
	if len(l.cache) > 0 {
		if it, ok := l.cache[key]; ok {
			l.mu.Unlock()
			return it, nil
		}
	}
	l.unsafeBatchSet()
	{{ end }}
	batch := l.batch
	pos := batch.keyIndex(l, key)
	l.mu.Unlock()

	return {{.ValType.String|loadThunkMissReturnType}}, func() ({{.ValType.String}}, error) {
		<-batch.done

		var data {{.ValType.String}}
		if pos < len(batch.data) {
			data = batch.data[pos]
		}

		var err error
		// its convenient to be able to return a single error for everything
		if len(batch.errors) == 1 {
			err = batch.errors[0]
		} else if batch.errors != nil {
			err = batch.errors[pos]
		}

		if err == nil {
			l.mu.Lock()
			l.unsafeSet(key, data)
			l.mu.Unlock()
		}

		return data, err
	}
}

// LoadAll fetches many keys at once. It will be broken into appropriate sized
// sub batches depending on how the loader is configured
func (l *{{.Name}}) LoadAll(keys []{{.KeyType}}) ([]{{.ValType.String}}, []error) {
	{{.ValType.Name|lcFirst}}s := make([]{{.ValType.String}}, len(keys))
	thunks := make(map[int]func() ({{.ValType.String}}, error), len(keys))
	errors := make([]error, len(keys))

	for i, key := range keys {
		if v, thunk :=  l.LoadThunk(key); thunk != nil {
			thunks[i] = thunk
		} else {
			{{.ValType.Name|lcFirst}}s[i] = v
		}
	}
	for i, thunk := range thunks {
		{{.ValType.Name|lcFirst}}s[i], errors[i] = thunk()
	}

	return {{.ValType.Name|lcFirst}}s, errors
}

// LoadAllThunk returns a function that when called will block waiting for a {{.ValType.Name}}s.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *{{.Name}}) LoadAllThunk(keys []{{.KeyType}}) (func() ([]{{.ValType.String}}, []error)) {
	thunks := make(map[int]func() ({{.ValType.String}}, error), len(keys))
	{{.ValType.Name|lcFirst}}s := make([]{{.ValType.String}}, len(keys))
 	for i, key := range keys {
		if v, thunk :=  l.LoadThunk(key); thunk != nil {
			thunks[i] = thunk
		} else {
			{{.ValType.Name|lcFirst}}s[i] = v
		}
	}
	return func() ([]{{.ValType.String}}, []error) {
		errors := make([]error, len(keys))
		for i, thunk := range thunks {
			{{.ValType.Name|lcFirst}}s[i], errors[i] = thunk()
		}
		return {{.ValType.Name|lcFirst}}s, errors
	}
}

// unsafePrime will prime the cache with the given key and value if the key does not exist. This method is not thread safe.
func (l *{{.Name}}) unsafePrime(key {{.KeyType}}, value {{.ValType.String}}, forceReplace bool) bool {
	var found bool
	{{ if not .DisableCacheExpiration }}
	if l.expireAfter <= 0 {
		// not using cache expiration
	{{ end }}
		if _, found = l.cache[key]; found && forceReplace {
			delete(l.cache, key)
		}
		if !found || forceReplace {
			{{- if .ValType.IsPtr }}
				// make a copy when writing to the cache, its easy to pass a pointer in from a loop var
				// and end up with the whole cache pointing to the same value.
				cpy := *value
				l.unsafeSet(key, &cpy)
			{{- else if .ValType.IsSlice }}
				// make a copy when writing to the cache, its easy to pass a pointer in from a loop var
				// and end up with the whole cache pointing to the same value.
				cpy := make({{.ValType.String}}, len(value))
				copy(cpy, value)
				l.unsafeSet(key, cpy)
			{{- else }}
				l.unsafeSet(key, value)
			{{- end }}
		}
	{{ if not .DisableCacheExpiration }}
	} else {
		// using cache expiration
		if _, found = l.cacheExpire[key]; found && forceReplace  {
			delete(l.cacheExpire, key)
		}
		if !found || forceReplace {
			{{- if .ValType.IsPtr }}
				// make a copy when writing to the cache, its easy to pass a pointer in from a loop var
				// and end up with the whole cache pointing to the same value.
				cpy := *value
				l.unsafeSet(key, &cpy)
			{{- else if .ValType.IsSlice }}
				// make a copy when writing to the cache, its easy to pass a pointer in from a loop var
				// and end up with the whole cache pointing to the same value.
				cpy := make({{.ValType.String}}, len(value))
				copy(cpy, value)
				l.unsafeSet(key, cpy)
			{{- else }}
				l.unsafeSet(key, value)
			{{- end }}
		}
	}
	{{ end }}
	return !found || forceReplace
}

// PrimeMany will prime the cache with the given keys and values. Value index is matched to key index.
func (l *{{.Name}}) PrimeMany(keys []{{.KeyType}}, values []{{.ValType.String}}) []bool {
	if len(keys) != len(values) {
		// keys and values must be the same length
		return make([]bool, len(keys))
	}
	ret := make([]bool, len(keys))
	l.mu.Lock()
	for i, key := range keys {
		ret[i] = l.unsafePrime(key, values[i], false)
	}
	l.mu.Unlock()
	return ret
}

// Prime the cache with the provided key and value. If the key already exists, no change is made
// and false is returned.
// (To forcefully prime the cache, clear the key first with loader.clear(key).prime(key, value).)
func (l *{{.Name}}) Prime(key {{.KeyType}}, value {{.ValType.String}}) bool {
	l.mu.Lock()
	found := l.unsafePrime(key, value, false)
	l.mu.Unlock()
	return found
}

// ForcePrime the cache with the provided key and value. If the key already exists, value is replaced
// (This removes the requirement to clear the key first with loader.clear(key).prime(key, value))
func (l *{{.Name}}) ForcePrime(key {{.KeyType}}, value {{.ValType.String}}) {
	l.mu.Lock()
	l.unsafePrime(key, value, true)
	l.mu.Unlock()
}

// Clear the value at key from the cache, if it exists
func (l *{{.Name}}) Clear(key {{.KeyType}}) {
	{{ if not .DisableCacheExpiration }}
	if l.expireAfter <= 0 {
		// not using cache expiration
	{{ end }}
		l.mu.Lock()
		delete(l.cache, key)
		l.mu.Unlock()
	{{ if not .DisableCacheExpiration }}
	} else {
		// using cache expiration
		l.mu.Lock()
		delete(l.cacheExpire, key)
		l.mu.Unlock()
	}
	{{ end }}
	if l.hookAfterClear != nil {
		l.hookAfterClear(key)
	}
}

// ClearAll clears all values from the cache
func (l *{{.Name}}) ClearAll() {
	{{ if not .DisableCacheExpiration }}
	if l.expireAfter <= 0 {
		// not using cache expiration
	{{ end}}
		l.mu.Lock()
		l.cache = make(map[{{.KeyType}}]{{.ValType.String}}, l.maxBatch)
		l.mu.Unlock()
	
	{{ if not .DisableCacheExpiration }}
	} else {
		// using cache expiration
		l.mu.Lock()
		l.cacheExpire = make(map[{{.KeyType}}]*{{.Name}}CacheItem, l.maxBatch)
		l.mu.Unlock()
	}
	{{ end }}
	if l.hookAfterClearAll != nil {
		l.hookAfterClearAll()
	}
}

{{ if not .DisableCacheExpiration }}
// ClearExpired clears all expired values from the cache if cache expiration is being used
func (l *{{.Name}}) ClearExpired() {
	if l.expireAfter > 0 {
		// using cache expiration
		tNow := time.Now().UnixNano()
		l.mu.Lock()
		for cacheKey, cacheItem := range l.cacheExpire {
			if cacheItem != nil && tNow > cacheItem.Expires {
				// value has expired
				delete(l.cacheExpire, cacheKey)
				if l.hookAfterExpired != nil {
					l.hookAfterExpired(cacheKey)
				}
			}
		}
		l.mu.Unlock()
	}
}

{{ end }}
// unsafeSet will set the key to value without any locks or checks. This method is not thread safe.
func (l *{{.Name}}) unsafeSet(key {{.KeyType}}, value {{.ValType.String}}) {
	{{ if not .DisableCacheExpiration }}
	if l.expireAfter <= 0 {
		// not using cache expiration
	{{ end }}
		if l.cache == nil {
			l.cache = make(map[{{.KeyType}}]{{.ValType.String}}, l.maxBatch)
		}
		l.cache[key] = value
	{{ if not .DisableCacheExpiration }}
	} else {
		// using cache expiration
		if l.cacheExpire == nil {
			l.cacheExpire = make(map[{{.KeyType}}]*{{.Name}}CacheItem, l.maxBatch)
		}
		l.cacheExpire[key] = &{{.Name}}CacheItem{Expires: time.Now().UnixNano()+l.expireAfter, Value: value}
	}
	{{ end }}
	if l.hookAfterSet != nil {
		l.hookAfterSet(key, value)
	}
}

// keyIndex will return the location of the key in the batch, if its not found
// it will add the key to the batch
func (b *{{.Name|lcFirst}}Batch) keyIndex(l *{{.Name}}, key {{.KeyType}}) int {
	if i, ok := b.keysMap[key]; ok {
		return i
	}

	pos := len(b.keysMap)
	b.keysMap[key] = pos
	b.keys = append(b.keys, key)
	if pos == 0 {
		go b.startTimer(l)
	}

	if l.maxBatch != 0 && pos >= l.maxBatch-1 {
		if !b.closing {
			b.closing = true
			l.batch = nil
			go b.end(l)
		}
	}

	return pos
}

// startTimer will wait the desired wait time before sending the batch unless another batch limit had been reached
func (b *{{.Name|lcFirst}}Batch) startTimer(l *{{.Name}}) {
	time.Sleep(l.wait)
	l.mu.Lock()

	// we must have hit a batch limit and are already finalizing this batch
	if b.closing {
		l.mu.Unlock()
		return
	}

	l.batch = nil
	l.mu.Unlock()

	b.end(l)
}

// end calls fetch and closes the done channel to unblock all thunks
func (b *{{.Name|lcFirst}}Batch) end(l *{{.Name}}) {
	if l.hookBeforeFetch != nil {
		l.hookBeforeFetch(b.keys, "{{.Name}}")
	}
	b.data, b.errors = l.fetch(b.keys)
	if l.hookAfterFetch != nil {
		l.hookAfterFetch(b.keys, "{{.Name}}")
	}
	close(b.done)
}
`))
